SELECT COUNT(*) FROM WESLEY_LIBRARY;
SELECT COUNT(*) FROM BOOKS_WESLEY;

SHOW TABLES;

DESCRIBE TABLE BOOKS_WESLEY;
DESCRIBE TABLE WESLEY_LIBRARY;
DESCRIBE TABLE LIBRARY_CATALOG_BOOKS;


-- Migrate rows from BOOKS_WESLEY that don't already exist in WESLEY_LIBRARY
INSERT INTO WESLEY_LIBRARY (
    ISBN, TITLE, AUTHOR, EDITION, PUBLISHER, DATE,
    DEWEY, LCCN, CATALOGNUMBER, PAGES, SOURCE
)
SELECT
    b.ISBN, b.TITLE, b.AUTHOR, b.EDITION, b.PUBLISHER, b.DATE,
    b.DEWEY, b.LCCN, b.CATALOGNUMBER, CAST(b.PAGES AS VARCHAR), b.SOURCE
FROM BOOKS_WESLEY b
WHERE b.ISBN NOT IN (SELECT ISBN FROM WESLEY_LIBRARY WHERE ISBN IS NOT NULL);


SELECT COUNT(*) FROM WESLEY_LIBRARY;

ALTER TABLE WESLEY_LIBRARY ADD COLUMN SUMMARY VARCHAR;
ALTER TABLE WESLEY_LIBRARY ADD COLUMN AUDIENCE VARCHAR;
ALTER TABLE WESLEY_LIBRARY ADD COLUMN CATEGORY VARCHAR;
ALTER TABLE WESLEY_LIBRARY ADD COLUMN TAGS VARCHAR;

SELECT TITLE, AUDIENCE, CATEGORY, TAGS, SUMMARY 
FROM WESLEY_LIBRARY 
WHERE SUMMARY IS NOT NULL 
LIMIT 10;



-- '3/12/2026'
CREATE TABLE IF NOT EXISTS AUDIT_LOG_WESLEY (
    ID              NUMBER AUTOINCREMENT PRIMARY KEY,
    ACTION          VARCHAR(50),   -- 'book_added', 'book_updated', 'book_deleted'
    ISBN            VARCHAR(20),
    TITLE           VARCHAR(500),
    PERFORMED_BY    VARCHAR(200),  -- will be 'system' for now, ready for user auth later
    PERFORMED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    NOTES           VARCHAR(1000)
);
